default: &default
  adapter: redis
  url: <%= "#{ ENV.fetch('REDIS_URL') { "redis://localhost:6379" } }/1/cable" %>

development:
  <<: *default
  channel_prefix: orbita_dev

test:
  adapter: test

production:
  <<: *default
  channel_prefix: orbita_prod
